import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/Navbar";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";
import ClientWrapper from "@/components/loader/ClientWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ghosi",
  description: "Generated by create next app",

   icons: {
        icon: '/image/logo.png',
      },
 
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <Navbar />
        <ClientWrapper>     
          {children}
        </ClientWrapper>
        <Footer />
      </body>
    </html>
  );
}
