import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/Navbar";
import Header from "@/components/landing/Header";
import Footer from "@/components/landing/Footer";
import ClientWrapper from "@/components/loader/ClientWrapper";
import { LoadingProvider } from "@/components/ui/LoadingProvider"; // Import the loading context provider
import Script from "next/dist/client/script";
import AnalyticsTracker from "@/components/analytics/AnalyticsTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ghosi",
  description: "Generated by create next app",

  icons: {
    icon: "/image/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`}
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingProvider>
          {" "}
          {/* Wrap the application with LoadingProvider */}
          <Header />
          <Navbar />
          {/* Tracks page changes */}
          <AnalyticsTracker />
          <ClientWrapper>{children}</ClientWrapper>
          <Footer />
        </LoadingProvider>
      </body>
    </html>
  );
}
